### ISSUE TITLE
Random seeds

### ISSUE THREAD

**Issue by donghwan1994** [igip-liu/SLC-Net#1]
Thanks for your wonderful work. In your papers, you used three random seeds for experiments. I want to know what seed you use for each trial.

**Comment by igip-liu** [comment]
In our experiments, we use random seeds of 1337, 1000, and 1, respectively.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Donghwan ***@***.***&gt;; 
发送时间: 2022年9月19日(星期一) 晚上7:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [igip-liu/SLC-Net] Random seeds (Issue #1)





 
Thanks for your wonderful work. In your papers, you used three random seeds for experiments. I wonder what seed you use for each trial.

**Comment by donghwan1994** [comment]
Thanks for your reply. I learned a lot through your paper and code.
